[project]
name = "robust_email_validator"
version = "0.1.0"
description = "Make email list with confidence"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dnspython>=2.7.0",
    "pydantic>=2.9.2",
    "requests>=2.32.3",
]
